### ISSUE TITLE
Browserify and bower seems to not work

### ISSUE THREAD

**Issue by jcampalo** [reflux/refluxjs#130]
Hi,

I've been triying to use Reflux in my project, but I don't have any idea why when I do `var Reflux = require('reflux');` Browserify cannot find module 'reflux', but it works well with React v0.12.1
